name: test-linux

on:
  pull_request:
  push:
    branches:
      - master
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  test-linux:
    runs-on: [m5large]
    steps:
      - run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install 14.15.1
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions"
